#!/usr/bin/env bash

# NOM_DEBUG=true
PWD=$(pwd)

APP=/srv/www/wiki.imbue.studio
GIT_DEPLOYMENT_ROOT=/usr/home/gollum/git

export GIT_DIR=$GIT_DEPLOYMENT_ROOT
export GIT_WORK_TREE=$APP

# system installation of rbenv 
export RBENV_ROOT=/srv/ruby/rbenv
# eval "$(rbenv init -)"
PATH=/srv/ruby/rbenv/shims:$PATH

git checkout -f || exit 0
cd $GIT_WORK_TREE || exit 0

if [[ -n $NOM_DEBUG ]]; then
  echo "USER: $USER"
  echo "HOME: $HOME"
  echo "PWD: $PWD"
  echo "PATH: $PATH"
  echo "RUBY: $(rbenv global)"
  echo "RUBY: $(rbenv local)"
  echo "RUBY: $(rbenv root)"
  echo "RUBY: $(rbenv version)"
  echo "BIN: $(which ruby)"
  echo "VER: $(ruby --version)"
fi

/srv/ruby/rbenv/shims/bundle check
/srv/ruby/rbenv/shims/bundle install --deployment --verbose

if [[ $? = 0 ]]; then
  ${APP}/gollum-server stop
  ${APP}/gollum-server start  
fi

